import type { iPost } from '../../types';

export const POSTS: iPost[] = [
  {
    _id: '1',
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: '/posts/post1.png',
    user: {
      _id: 'u1',
      username: 'johndoe',
      profileImg: '/avatars/boy1.png',
      fullName: 'John Doe',
    },
    comments: [
      {
        _id: 'c1',
        text: 'Nice Tutorial',
        user: {
          _id: 'u2',
          username: 'janedoe',
          profileImg: '/avatars/girl1.png',
          fullName: 'Jane Doe',
        },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    likes: ['u2', 'u3', 'u4', 'u5'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '2',
    text: 'How you guys doing? 😊',
    user: {
      _id: 'u1',
      username: 'johndoe',
      profileImg: '/avatars/boy2.png',
      fullName: 'John Doe',
    },
    comments: [
      {
        _id: 'c2',
        text: 'Nice Tutorial',
        user: {
          _id: 'u3',
          username: 'janedoe',
          profileImg: '/avatars/girl2.png',
          fullName: 'Jane Doe',
        },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    likes: ['u2', 'u3', 'u4', 'u5'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '3',
    text: 'Astronaut in a room of drawers, generated by Midjourney. 🚀',
    img: '/posts/post2.png',
    user: {
      _id: 'u1',
      username: 'johndoe',
      profileImg: '/avatars/boy3.png',
      fullName: 'John Doe',
    },
    comments: [],
    likes: ['u2', 'u3', 'u4', 'u5', 'u6', 'u7'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: '4',
    text: "I'm learning GO this week. Any tips? 🤔",
    img: '/posts/post3.png',
    user: {
      _id: 'u1',
      username: 'johndoe',
      profileImg: '/avatars/boy3.png',
      fullName: 'John Doe',
    },
    comments: [
      {
        _id: 'c3',
        text: 'Nice Tutorial',
        user: {
          _id: 'u4',
          username: 'janedoe',
          profileImg: '/avatars/girl3.png',
          fullName: 'Jane Doe',
        },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    likes: ['u2', 'u3', 'u4', 'u5', 'u6', 'u7', 'u8', 'u9', 'u10'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: 'u1',
    fullName: 'John Doe',
    username: 'johndoe',
    profileImg: '/avatars/boy2.png',
  },
  {
    _id: 'u2',
    fullName: 'Jane Doe',
    username: 'janedoe',
    profileImg: '/avatars/girl1.png',
  },
  {
    _id: 'u3',
    fullName: 'Bob Doe',
    username: 'bobdoe',
    profileImg: '/avatars/boy3.png',
  },
  {
    _id: 'u4',
    fullName: 'Daisy Doe',
    username: 'daisydoe',
    profileImg: '/avatars/girl2.png',
  },
];
